---
global:
  resolve_timeout: 5m
  smtp_smarthost: mail.test.ru:25
  smtp_from: alerts@test.ru

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 6h
  receiver: 'email'
  routes:
    #- receiver: 'email'
    #  group_by: ['alertname', 'instance']
    #  match:
    #    severity: critical
    - receiver: 'email'
      group_by: ['service']
      match_re:
        alertname: 'Server.*Down'
    - receiver: 'email'
      group_by: ['service']
      match_re:
        alertname: 'WebServer.*Down'

receivers:
  - name: 'email'
    email_configs:
      - to: 'admins@test.ru'
        send_resolved: true

inhibit_rules:
  - source_match_re:
      alertname: 'Server.*Down'
    target_match:
      alertname: 'WebGatewayDown'
